version: "3"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql/
    ports:
      - "3306:3306"

  django:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - bash
      - -c
      - |
        /wait-for-it.sh db:${DB_PORT}
        java -jar /app.jar
    volumes:
      - .:/app/
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=${DB_DRIVER}
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_SHOW_SQL=${DB_SHOW_SQL}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${DB_HIBERNATE_DDL_AUTO}
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=${DB_FORMAT_SQL}

volumes:
  db_data: {}